### ISSUE TITLE
Compiling LATTE-LAMMPS as dynamic shared library

### ISSUE THREAD

**Issue by tomswinburne** [lanl/LATTE#46]
I have successfully compiled LATTE-LAMMPS as a binary (from the lammps/src directory):
make mpi
and as a static library:
make mpi mode=lib

but when compiling as a dynamic library
make mpi mode=shlib

I get the following error:
/usr/bin/ld: ../../lib/latte/liblink/liblatte.a(latte_lib.o): relocation R_X86_64_32 against `__constants_mod_MOD_box' can not be used when making a shared object; recompile with -fPIC
../../lib/latte/liblink/liblatte.a: error adding symbols: Bad value

We added -fPIC to the makefile, error persisted

Commenting out "half" of lib_latte we get the same error but with "rodata" data routine so it doesn't seem to be from __constants_mod_MOD_box

When everything is commented out in latte_lib.f90 the compilation works. 

Any help much appreciated!

Tom

**Comment by nicolasbock** [comment]
Did you clean out all of the built files before you started the shared library build? This sounds like `liblatte.a` was not compiled for shared libraries.

**Comment by tomswinburne** [comment]
Hi Guys,
It now compiles! 
We only added -fPIC to LINKFLAGS not FFLAGS in makefile.CHOICES.... Friday afternoon.... 
Thanks!
Tom

**Comment by nicolasbock** [comment]
I'll close this issue then. Please open a new one in case you run into any difficulties.
